### ISSUE TITLE
Light start with js frameworks using Marionette

### ISSUE THREAD

**Issue by denar90** [marionettejs/blog#34]
I think most of you aware about post https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f#.px3ilttei how it's hard to start learning js nowadays.
For newbies it's hard to try smth fancy like Angular2.0 because of big stack of technologies (typescript, jsx etc..)
I propose make post for people who already new js basics and wanna try some framework. Of course it wil be about Marionette.js 😄

**Comment by scott-w** [comment]
So a new post about how Mn is easier for a newcomer to JS and frameworks? I'd be in support of that.

**Comment by denar90** [comment]
Yeap just some basic. How to up and running. Maybe some additional stuff, don't now exactly.
