### ISSUE TITLE
Marionette's future major releases blog post

### ISSUE THREAD

**Issue by jmeas** [marionettejs/blog#6]
v3 and v4.

An Architecture Update and a View Update. I'd like to write this one, too, unless someone else is just jonesin' to write a blog post about our future major releases. Just lemme know – I got 2 others in the works so it's nbd.

**Comment by denar90** [comment]
@jmeas would you like to write something about v3 version. Created related issue #28

**Comment by jmeas** [comment]
@denar90 don't think I'll have time I'm afraid :(

**Comment by denar90** [comment]
Closing due to published post about v3
